Repository hack4impact/maps4all, pull requests merged in 2018-04, with the labels that each got.

#165 New "moderator" role
  app/admin/views.py
  app/models/user.py
  app/suggestion/views.py
  app/templates/admin/index.html
  app/templates/bulk_resource/upload.html
  app/templates/macros/nav_macros.html
Labels: database

#193 Improve upload CSV frontend
  app/bulk_resource/views.py
  app/models/csv.py
  app/models/resource.py
  app/templates/bulk_resource/review_desc_options.html
  app/templates/bulk_resource/set_descriptor_types.html
  app/templates/bulk_resource/upload.html
Labels: ready

#190 Upload descriptor refactoring
  app/bulk_resource/forms.py
  app/bulk_resource/helpers.py
  app/bulk_resource/views.py
  app/descriptor/forms.py
  app/models/resource.py
  app/templates/contact/index.html
  app/templates/main/index.html
Labels: database, in progress

#192 Download uses semicolons to separate option descriptor values
  app/single_resource/views.py
  app/templates/bulk_resource/upload.html
Labels: ready
